//
//  AnalyticsEvent.swift
//  Core
//
//  Created by Klim on 10/11/25.
//

import Foundation

public enum AnalyticsEvent: String, Codable, Sendable {
    case appOpened = "APP_OPENED"
    case feedPageOpened = "FEED_PAGE_OPENED"
    case landingPageOpened = "LANDING_PAGE_OPENED"
    case onboardingPageOpened = "ONBOARDING_PAGE_OPENED"
    case dashboardPageOpened = "DASHBOARD_PAGE_OPENED"
    case profilePageOpened = "PROFILE_PAGE_OPENED"
    case importPageOpened = "IMPORT_PAGE_OPENED"
    case termsPageOpened = "TERMS_PAGE_OPENED"
    case privacyPolicyPageOpened = "PRIVACY_POLICY_PAGE_OPENED"
    case refundsPageOpened = "REFUNDS_PAGE_OPENED"
    case realtimeWidgetOpened = "REALTIME_WIDGET_OPENED"
    case realtimeWidgetClosed = "REALTIME_WIDGET_CLOSED"
    case realtimeSessionConnecting = "REALTIME_SESSION_CONNECTING"
    case realtimeSessionConnected = "REALTIME_SESSION_CONNECTED"
    case realtimeSessionDisconnecting = "REALTIME_SESSION_DISCONNECTING"
    case realtimeSessionDisconnected = "REALTIME_SESSION_DISCONNECTED"
    case realtimeSessionFailed = "REALTIME_SESSION_FAILED"
    case transactionOpened = "TRANSACTION_OPENED"
    case transactionClosed = "TRANSACTION_CLOSED"
    case onboardingStepCompleted = "ONBOARDING_STEP_COMPLETED"
    case onboardingAllAnswered = "ONBOARDING_ALL_ANSWERED"
    case onboardingSignupClicked = "ONBOARDING_SIGNUP_CLICKED"
    case onboardingSignupCompleted = "ONBOARDING_SIGNUP_COMPLETED"
    case onboardingSignupFailed = "ONBOARDING_SIGNUP_FAILED"
    case paywallClicked = "PAYWALL_CLICKED"
    case paywallModalOpened = "PAYWALL_MODAL_OPENED"
    case stripePurchaseInitiated = "STRIPE_PURCHASE_INITIATED"
    case stripePortalOpened = "STRIPE_PORTAL_OPENED"
    case feedDemoLoaded = "FEED_DEMO_LOADED"
    case addTransactionModalOpened = "ADD_TRANSACTION_MODAL_OPENED"
    case addTransactionModalClosed = "ADD_TRANSACTION_MODAL_CLOSED"
    case addTargetModalOpened = "ADD_TARGET_MODAL_OPENED"
    case addTargetModalClosed = "ADD_TARGET_MODAL_CLOSED"
    case connectDeviceOpened = "CONNECT_DEVICE_OPENED"
    case connectDeviceOptionSelected = "CONNECT_DEVICE_OPTION_SELECTED"
    case connectDeviceTutorialClicked = "CONNECT_DEVICE_TUTORIAL_CLICKED"
    case connectDeviceWebhookUrlCopied = "CONNECT_DEVICE_WEBHOOK_URL_COPIED"
    case connectDeviceClosed = "CONNECT_DEVICE_CLOSED"
    case notificationsEnabled = "NOTIFICATIONS_ENABLED"
    case notificationsDisabled = "NOTIFICATIONS_DISABLED"
    case importFileSelected = "IMPORT_FILE_SELECTED"
    case importFileUnlocked = "IMPORT_FILE_UNLOCKED"
    case importFileUnlockFailed = "IMPORT_FILE_UNLOCK_FAILED"
    case importFileJobSubmitted = "IMPORT_FILE_JOB_SUBMITTED"
    case importFileJobPageUploaded = "IMPORT_FILE_JOB_PAGE_UPLOADED"
    case importFileJobAllPagesUploaded = "IMPORT_FILE_JOB_ALL_PAGES_UPLOADED"
    case importFileJobStartRequested = "IMPORT_FILE_JOB_START_REQUESTED"
    case importFileJobRequestFailed = "IMPORT_FILE_JOB_REQUEST_FAILED"
    case signedOut = "SIGNED_OUT"
    case manualTransactionAdded = "MANUAL_TRANSACTION_ADDED"
    case manualTransactionFailed = "MANUAL_TRANSACTION_FAILED"
    case targetStoreSaveForPageData = "TARGET_STORE_SAVE_FOR_PAGE_DATA"
    case targetRestoreFromSaveForPage = "TARGET_RESTORE_FROM_SAVE_FOR_PAGE"
    case targetAdded = "TARGET_ADDED"
    case targetAddFailed = "TARGET_ADD_FAILED"
    case targetTopupOk = "TARGET_TOPUP_OK"
    case targetTopupFailed = "TARGET_TOPUP_FAILED"
    case targetDatesChanged = "TARGET_DATES_CHANGED"
    case targetDatesChangeFailed = "TARGET_DATES_CHANGE_FAILED"
    case targetCompleted = "TARGET_COMPLETED"
    case targetCompleteFailed = "TARGET_COMPLETE_FAILED"
    case targetArchived = "TARGET_ARCHIVED"
    case targetArchiveFailed = "TARGET_ARCHIVE_FAILED"
    case transactionDeleted = "TRANSACTION_DELETED"
    case transactionDeleteFailed = "TRANSACTION_DELETE_FAILED"
    case transactionUpdated = "TRANSACTION_UPDATED"
    case transactionUpdateFailed = "TRANSACTION_UPDATE_FAILED"
    case updatesPageOpened = "UPDATES_PAGE_OPENED"
    case faqItemOpened = "FAQ_ITEM_OPENED"
    case faqItemClosed = "FAQ_ITEM_CLOSED"
}

